### PR TITLE
fix: security fixes for semossweb packages

### PR DESCRIPTION
**Pull request by radkalyan**
## Description
Security fixes for critical and high issues

## Changes Made
1. @vitest/browser -> Upgraded packages vitest, @vitest/ui , @vitest/browser-playwright, @vitest/coverage-v8, @vitest/browser to 4.1.6. All these packages must be upgraded together to prevent dependency issues
2. serialize-javascript -> Upgraded rollup/plugin-terser and mocha: pnpm up -r @rollup/plugin-terser@^1.0.0; pnpm up -r [mocha@^11.7.6](mailto:mocha@%5e11.7.6). This upgrade for rollup/plugin-terser automatically upgraded serialize-javascript within the package to 7.0.5. However this did not upgrade it within mocha. I had to add an explicit override to upgrade serialize-javascript within mocha. Override: "mocha>serialize-javascript": "7.0.5"
3. minimatch -> updated jest to 30.4.2; eslint, eslint-plugin-react-hooks, eslint-plugin-react-refresh to the latest major versions; rimraf to latest 3.x; glob updated to latest 8.x and 10.x versions - These updates bumped up the various minimatch pkg versions to 3.1.5, 5.1.9, 9.0.9 
4. shell-quote-> Updated parent package npm-run-all to 4.1.5. This re-resolved the shell-quote pkg and pulled the latest v1.8.4 version. 

## How to Test

1. Pull the latest code to your local Semoss setup; Run the app end to end and test the application

### CODE REVIEW

**Review by antgibson96 — APPROVED** [review]

**Comment by tevanburen** [comment]
Hey @radkalyan - this PR is breaking the `dev` build. The security bump pulled in `minipass@7.1.3` (transitive dep), which ships ESM types that are incompatible with the project's current TypeScript config:

```
@semoss/cli:build: ../../node_modules/.pnpm/minipass@7.1.3/node_modules/minipass/dist/esm/index.d.ts(14,117): error TS2315: Type 'EventEmitter' is not generic.
 ELIFECYCLE  Command failed with exit code 1.
 Failed: @semoss/cli#build
```

Tracked via `git bisect` — `084eb475` is the first bad commit. Likely needs either a `minipass` version pin or a `tsconfig` fix in `packages/cli`.
